spring:
  config:
    activate:
      on-profile: staging
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
    connect-retries: 20
    connect-retries-interval: 2

management:
  endpoint:
    health:
      show-details: never
      show-components: never

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

inventory:
  enabled: false
